// src/components/Navbar.vue
<template>
    <header class="bg-dark p-2 text-white">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand"
                    style="-webkit-user-select: none; /* Safari */
                        -moz-user-select: none; /* Firefox */
                        -ms-user-select: none; /* IE10+/Edge */
                        user-select: none; /* Standard */">
                    luuk180
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div  class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li>
                            <div v-if="home">
                                <router-link class="nav-link px-3 text-secondary" to="/">Home</router-link>
                            </div>
                            <div v-else>
                                <router-link class="nav-link px-3 text-white" to="/">Home</router-link>
                            </div>
                        </li>
                        <li>
                            <div v-if="projects">
                                <router-link class="nav-link px-3 text-secondary" to="/projects">Projects</router-link>
                            </div>
                            <div v-else>
                                <router-link class="nav-link px-3 text-white" to="/projects">Projects</router-link>
                            </div>
                        </li>
                        <li>
                            <div v-if="cv">
                                <router-link class="nav-link px-3 text-secondary" to="/cv">CV</router-link>
                            </div>
                            <div v-else>
                                <router-link class="nav-link px-3 text-white" to="/cv">CV</router-link>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
</template>

<script>

export default {
  data () {
    return {
      home: false,
      projects: false,
      cv: false,
    }
  },
  watch: {
    '$route' () {
      switch (this.$route.path) {
        case "/":
          this.home = true;
          this.projects = false;
          this.cv = false;
          break;
        case "/projects":
          this.projects = true;
          this.home = false;
          this.cv = false;
          break;
        case "/cv":
          this.cv = true;
          this.home = false;
          this.projects = false;
          break;
      }
    }
  }
}
</script>

// components/navbar.tsx
import Link from "next/link";
import {useRouter} from "next/router";
import styles from '@/styles/navbar.module.css';

export default function NavBar(){
    const router = useRouter();
    return <div>
        <nav className="navbar navbar-expand-sm bg-dark navbar-dark">
            <div className="container-fluid">
                <div className={styles.logo}>
                    <a className="navbar-brand">
                        luuk180
                    </a>
                </div>
                <button className="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapsibleNavbar">
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul className="navbar-nav">
                        <li>
                            {
                                router.route === "/" ?
                                    <Link className="nav-link px-3 text-secondary" href="/">Home</Link>:
                                    <Link className="nav-link px-3 text-white" href="/">Home</Link>
                            }
                        </li>
                        <li>
                            {
                                router.route === "/projects" ?
                                    <Link className="nav-link px-3 text-secondary" href="/projects">Projects</Link>:
                                    <Link className="nav-link px-3 text-white" href="/projects">Projects</Link>
                            }
                        </li>
                        <li>
                            {
                                router.route === "/cv" ?
                                    <Link className="nav-link px-3 text-secondary" href="/cv">CV</Link>:
                                    <Link className="nav-link px-3 text-white" href="/cv">CV</Link>
                            }
                        </li>
                        <li>
                            {
                                router.route === "/about" ?
                                    <Link className="nav-link px-3 text-secondary" href="/about">About</Link>:
                                    <Link className="nav-link px-3 text-white" href="/about">About</Link>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
}
